server:
  port: 8092
  servlet:
    context-path: /property-view

spring:
  application:
    name: hotelapp

  profiles:
    active: dev

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
